format_version: v1.0
type: UniqueComponent
attributes: {id: appWincSerialBridge}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: APP_USART_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: appWincSerialBridge, value: SERCOM2}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: uart}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom2}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM2_UART}
- type: ElementPosition
  attributes: {x: '530', y: '246', id: appWincSerialBridge}
