package:
  format-version: "1.0.0"
  name: "wireless_wifi"
  type: "api"
  status: "production"
  required: true
  version: "3.9.1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.17.0"
    - name: "core"
      type: "package"
      version: "3.13.0"
    - name: "net"
      type: "package"
      version: "3.10.0"
    - name: "bsp"
      type: "package"
      version: "3.16.0"
      
