package:
  format-version: "1.0.0"
  name: "wireless_wifi"
  type: "api"
  status: "production"
  required: false
  version: "v3.10.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.18.2"
    - name: "core"
      type: "package"
      version: "v3.13.2"
    - name: "net"
      type: "package"
      version: "v3.11.0"
    - name: "bsp"
      type: "package"
      version: "v3.17.0"
      
