package:
  format-version: "1.0.0"
  name: "wireless_wifi"
  type: "api"
  status: "production"
  required: false
  version: "v3.12.1"

  dependencies:
    - name: "net"
      type: "package"
      version: "v3.13.0"
      
