configName: sam_d21_xpro_winc3400
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMD21J18A
projectName: ''
settings:
  PackageFilter: bsp;core;crypto;cryptoauthlib;csp;net;wireless;wsg_dev;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.104\samd21a\atdf\ATSAMD21J18A.atdf
