format_version: v1.0
type: UniqueComponent
attributes: {id: drvWifiWinc}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_10}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_11}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_12}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_13}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_14}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_15}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_3}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_4}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_5}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_6}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_7}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_8}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_9}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'false'}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_EIC_SRC_SELECT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: '7'}
  - type: String
    attributes: {id: DRV_WIFI_WINC_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: SERCOM4}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_RX_DMA_CHANNEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: '1'}
  - type: Menu
    attributes: {id: DRV_WIFI_WINC_SPI_MENU}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_SYS_DMA_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'true'}
  - type: File
    attributes: {id: DRV_WIFI_WINC_SYS_RTOS_TASK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: DRV_WIFI_WINC_TX_DMA_CHANNEL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: '0'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_TX_RX_DMA}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DRV_WIFI_WINC_TX_RX_DMA_EN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvWifiWinc, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: drv_spi_dependency}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: DirectDependency
    attributes: {id: spi_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom4}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM4_SPI}
- type: ElementPosition
  attributes: {x: '168', y: '262', id: drvWifiWinc}
