/*** WiFi Driver Configuration ***/
<#if DRV_WIFI_WINC_INT_SRC == "EIC">
#define WDRV_WINC_EIC_SOURCE                EIC_PIN_${DRV_WIFI_WINC_EIC_SRC_SELECT}
<#elseif DRV_WIFI_WINC_INT_SRC == "External_Interrupt">
<#elseif DRV_WIFI_WINC_INT_SRC == "Change_Notification">
#define WDRV_WINC_INT_SOURCE INT_SOURCE_CHANGE_NOTICE
#define WDRV_WINC_INT_SOURCE_CN_PORT WDRV_WINC_INT_PORT
</#if>
<#if -1 < DRV_WIFI_WINC_SPI_INST_IDX>
#define WDRV_WINC_SPI_INDEX                 DRV_SPI_INDEX_${DRV_WIFI_WINC_SPI_INST_IDX}
</#if>
<#if DRV_WIFI_WINC_DRIVER_MODE == "Ethernet Mode">
#define WDRV_WINC_NETWORK_MODE_ETHERNET
<#else>
#define WDRV_WINC_NETWORK_MODE_SOCKET
</#if>
<#if DRV_WIFI_WINC_DEVICE == "WINC1500">
#define WDRV_WINC_DEVICE_WINC1500
<#if DRV_WIFI_WINC1500_VERSION == "19.5.4">
<#elseif DRV_WIFI_WINC1500_VERSION == "19.6.1">
#define WDRV_WINC_DEVICE_SPLIT_INIT
#define WDRV_WINC_DEVICE_ENTERPRISE_CONNECT
#define WDRV_WINC_DEVICE_EXT_CONNECT_PARAMS
#define WDRV_WINC_DEVICE_BSS_ROAMING
#define WDRV_WINC_DEVICE_FLEXIBLE_FLASH_MAP
<#if DRV_WIFI_WINC_DRIVER_MODE == "Socket Mode">
#define WDRV_WINC_DEVICE_CONF_NTP_SERVER
#define WDRV_WINC_DEVICE_HOST_FILE_DOWNLOAD
#define WDRV_WINC_DEVICE_SOFT_AP_EXT
<#else>
#define WDRV_WINC_DEVICE_DYNAMIC_BYPASS_MODE
</#if>
#define WDRV_WINC_DEVICE_MULTI_GAIN_TABLE
</#if>
<#elseif DRV_WIFI_WINC_DEVICE == "WINC3400">
#define WDRV_WINC_DEVICE_WINC3400
#define WDRV_WINC_DEVICE_SPLIT_INIT
#define WDRV_WINC_DEVICE_MULTI_GAIN_TABLE
<#if DRV_WIFI_WINC3400_VERSION == "1.2.2">
<#elseif DRV_WIFI_WINC3400_VERSION == "1.3.0">
#define WDRV_WINC_DEVICE_ENTERPRISE_CONNECT
#define WDRV_WINC_DEVICE_EXT_CONNECT_PARAMS
#define WDRV_WINC_DEVICE_BSS_ROAMING
<#if DRV_WIFI_WINC_DRIVER_MODE == "Socket Mode">
#define WDRV_WINC_DEVICE_CONF_NTP_SERVER
#define WDRV_WINC_DEVICE_SOFT_AP_EXT
<#else>
#define WDRV_WINC_DEVICE_DYNAMIC_BYPASS_MODE
</#if>
</#if>
<#if DRV_WIFI_WINC_USE_BLUETOOTH_WINC3400>
#define WDRV_WINC_ENABLE_BLE
</#if>
</#if>
<#if DRV_WIFI_WINC_LOG_LEVEL == "None">
#define WDRV_WINC_DEBUG_LEVEL               WDRV_WINC_DEBUG_TYPE_NONE
<#elseif DRV_WIFI_WINC_LOG_LEVEL == "Error">
#define WDRV_WINC_DEBUG_LEVEL               WDRV_WINC_DEBUG_TYPE_ERROR
<#elseif DRV_WIFI_WINC_LOG_LEVEL == "Inform">
#define WDRV_WINC_DEBUG_LEVEL               WDRV_WINC_DEBUG_TYPE_INFORM
<#elseif DRV_WIFI_WINC_LOG_LEVEL == "Trace">
#define WDRV_WINC_DEBUG_LEVEL               WDRV_WINC_DEBUG_TYPE_TRACE
<#elseif DRV_WIFI_WINC_LOG_LEVEL == "Verbose">
#define WDRV_WINC_DEBUG_LEVEL               WDRV_WINC_DEBUG_TYPE_VERBOSE
</#if>
