/*** WiFi PIC32MZW1 Driver Configuration ***/
<#if sys_debug?? && sys_debug.SYS_DEBUG_USE_CONSOLE?? && DRV_WIFI_PIC32MZW1_USE_SYS_DEBUG && sys_debug.SYS_DEBUG_USE_CONSOLE>
    <#lt>#define WDRV_PIC32MZW1_DEVICE_USE_SYS_DEBUG
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "None">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_NONE
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "Error">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_ERROR
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "Inform">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_INFORM
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "Trace">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_TRACE
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "Verbose">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_VERBOSE
</#if>
<#if DRV_WIFI_PIC32MZW1_SUPPORT_SAE == true>
#define WDRV_PIC32MZW_WPA3_PERSONAL_SUPPORT
</#if>
<#if DRV_WIFI_PIC32MZW1_REQUIRE_BA414E == true>
#define WDRV_PIC32MZW_BA414E_SUPPORT
</#if>
<#if DRV_WIFI_PIC32MZW1_REQUIRE_BIGINTSW == true>
#define WDRV_PIC32MZW_BIGINTSW_SUPPORT
</#if>
<#if DRV_WIFI_PIC32MZW1_SUPPORT_ENTERPRISE == true>
#define WDRV_PIC32MZW_ENTERPRISE_SUPPORT
/* Wolfssl : Support openssl based server certs having 'basic constraint' extension value as non-boolean. */
#define WOLFSSL_X509_BASICCONS_INT
/* Wolfssl : Don't validate key-usage extension of the certificate */
#define IGNORE_KEY_EXTENSIONS
</#if>
<#if DRV_WIFI_PIC32MZW1_REQUIRE_WOLFSSL == true>
#define WDRV_PIC32MZW_WOLFSSL_SUPPORT
</#if>
#define WDRV_PIC32MZW_ALARM_PERIOD_1MS          ${DRV_WIFI_PIC32MZW1_ALARM_PERIOD_1MS}
#define WDRV_PIC32MZW_ALARM_PERIOD_MAX          ${DRV_WIFI_PIC32MZW1_ALARM_PERIOD_MAX}