/*** WiFi PIC32MZW1 Driver Configuration ***/
<#if sys_debug?? && sys_debug.SYS_DEBUG_USE_CONSOLE?? && DRV_WIFI_PIC32MZW1_USE_SYS_DEBUG && sys_debug.SYS_DEBUG_USE_CONSOLE>
    <#lt>#define WDRV_PIC32MZW1_DEVICE_USE_SYS_DEBUG
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "None">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_NONE
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "Error">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_ERROR
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "Inform">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_INFORM
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "Trace">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_TRACE
<#elseif DRV_WIFI_PIC32MZW1_LOG_LEVEL == "Verbose">
    <#lt>#define WDRV_PIC32MZW_DEBUG_LEVEL               WDRV_PIC32MZW_DEBUG_TYPE_VERBOSE
</#if>
<#if DRV_WIFI_PIC32MZW1_SUPPORT_WPA3 == true>
#define WDRV_PIC32MZW_WPA3_SUPPORT
</#if>
<#if DRV_WIFI_PIC32MZW1_REQUIRE_BA414E == true>
#define WDRV_PIC32MZW_BA414E_SUPPORT
</#if>
