format_version: v1.0
configName: sam_d21_xpro_winc1500
folderName: sam_d21_xpro_winc1500
frameworkPath: C:\microchip\mccrepos
processor: ATSAMD21J18A
projectName: sam_d21_xpro_winc1500
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAMD21_DFP\3.6.144\samd21a\atdf\ATSAMD21J18A.atdf
